from fpdf import FPDF
from datetime import datetime


class _ReportPDF(FPDF):
    def header(self):
        self.set_fill_color(15, 23, 42)
        self.rect(0, 0, 210, 28, "F")
        self.set_text_color(255, 255, 255)
        self.set_font("Helvetica", "B", 16)
        self.cell(0, 10, "Data Quality Monitoring Report", ln=True, align="C")
        self.set_font("Helvetica", "", 9)
        self.cell(0, 6, datetime.now().strftime("Generated on %Y-%m-%d %H:%M:%S"), ln=True, align="C")
        self.ln(10)

    def footer(self):
        self.set_y(-15)
        self.set_font("Helvetica", "", 8)
        self.set_text_color(120, 120, 120)
        self.cell(0, 10, "Generated by Data Quality Monitoring System", align="C")

    def section_title(self, title):
        self.set_text_color(15, 23, 42)
        self.set_font("Helvetica", "B", 13)
        self.cell(0, 9, title, ln=True)
        self.set_draw_color(220, 220, 220)
        self.line(10, self.get_y(), 200, self.get_y())
        self.ln(4)


def _safe_text(value):
    return str(value).encode("latin-1", "replace").decode("latin-1")


def _severity(count):
    if count == 0:
        return "Low"
    if count <= 3:
        return "Medium"
    if count <= 10:
        return "High"
    return "Critical"


def _recommendations(issue_counts):
    recs = []
    if issue_counts.get("Missing Values", 0) > 0:
        recs.append("Fill or review missing values before production use.")
    if issue_counts.get("Duplicates", 0) > 0:
        recs.append("Remove duplicate rows to avoid inaccurate analysis.")
    if issue_counts.get("Invalid Email", 0) > 0:
        recs.append("Correct invalid email addresses.")
    if issue_counts.get("Invalid Phone", 0) > 0:
        recs.append("Verify and standardize phone numbers.")
    if issue_counts.get("Invalid Age", 0) > 0:
        recs.append("Review invalid age values.")
    if issue_counts.get("Invalid Join Date", 0) > 0:
        recs.append("Fix invalid date formats.")
    return recs or ["No major data quality issues found."]


def generate_pdf_report(file_name: str, records: int, columns: int, score: float, issue_counts: dict) -> bytes:
    pdf = _ReportPDF()
    pdf.add_page()

    total_issues = sum(issue_counts.values())

    pdf.section_title("Executive Summary")
    pdf.set_fill_color(245, 247, 250)
    pdf.set_text_color(20, 20, 20)

    summary = [
        ("File Name", _safe_text(file_name)),
        ("Total Records", records),
        ("Total Columns", columns),
        ("Total Issues", total_issues),
        ("Quality Score", f"{score}%"),
    ]

    for label, value in summary:
        pdf.set_font("Helvetica", "B", 10)
        pdf.cell(55, 8, _safe_text(label), border=1, fill=True)
        pdf.set_font("Helvetica", "", 10)
        pdf.cell(125, 8, _safe_text(value), border=1, ln=True)

    pdf.ln(6)

    pdf.section_title("Issue Breakdown")
    pdf.set_fill_color(15, 23, 42)
    pdf.set_text_color(255, 255, 255)
    pdf.set_font("Helvetica", "B", 10)

    pdf.cell(90, 8, "Issue Type", border=1, fill=True)
    pdf.cell(40, 8, "Count", border=1, align="C", fill=True)
    pdf.cell(50, 8, "Severity", border=1, align="C", ln=True, fill=True)

    pdf.set_text_color(20, 20, 20)
    pdf.set_font("Helvetica", "", 10)

    for issue, count in issue_counts.items():
        pdf.cell(90, 8, _safe_text(issue), border=1)
        pdf.cell(40, 8, str(count), border=1, align="C")
        pdf.cell(50, 8, _severity(int(count)), border=1, align="C", ln=True)

    pdf.ln(6)

    pdf.section_title("Data Quality Assessment")
    assessment = (
        f"The dataset contains {records} records and {columns} columns. "
        f"The overall quality score is {score}%. "
        f"A total of {total_issues} data quality issues were detected during this scan."
    )
    pdf.set_font("Helvetica", "", 10)
    pdf.multi_cell(180, 7, _safe_text(assessment))

    pdf.ln(4)

    pdf.section_title("Recommendations")
    pdf.set_font("Helvetica", "", 10)

    for rec in _recommendations(issue_counts):
     pdf.set_x(15)
     pdf.multi_cell(180, 7, "- " + _safe_text(rec))
     pdf.ln(1) 

    return bytes(pdf.output())